version: '3.8'

services:
  banklab: # Frontend SvelteKit App
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banklab
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    external: true # Specify that this network is created elsewhere (in your main docker-compose.yml)
    name: web-network # The name of the external network
